name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npx eslint . --ignore-pattern 'chart.min.js' --ignore-pattern '**/dist/**' --ignore-pattern '**/build/**'
      - name: Prettier Check
        run: npx prettier --check .
      - name: Run tests
        run: echo "No tests yet"
      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.html
